apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-pod
  name: busybox-pod
  namespace: m-shukurjonov
spec:
  containers:
  - command: ["sleep", "3600"]
    image: busybox
    name: busybox-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
