apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx1
    project: practice
    author: muzaffar
  name: nginx1
  namespace: m-shukurjonov
spec:
  containers:
  - image: nginx:latest
    name: nginx1
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
